/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    'dusk.login': [
      {
        name: 'userId';
        required: true;
      },
      {
        name: 'guard';
        required: false;
      },
    ];
    'dusk.logout': [
      {
        name: 'guard';
        required: false;
      },
    ];
    'dusk.user': [
      {
        name: 'guard';
        required: false;
      },
    ];
    'sanctum.csrf-cookie': [];
    home: [];
    dashboard: [];
    'profile.edit': [];
    'profile.update': [];
    'profile.destroy': [];
    'password.edit': [];
    'password.update': [];
    appearance: [];
    register: [];
    login: [];
    'password.request': [];
    'password.email': [];
    'password.reset': [
      {
        name: 'token';
        required: true;
      },
    ];
    'password.store': [];
    'verification.notice': [];
    'verification.verify': [
      {
        name: 'id';
        required: true;
      },
      {
        name: 'hash';
        required: true;
      },
    ];
    'verification.send': [];
    'password.confirm': [];
    logout: [];
    'storage.local': [
      {
        name: 'path';
        required: true;
      },
    ];
  }
}
export {};
