import type { ZorahConfig } from 'zorah-js';

declare global {
  interface Window {
    Zorah?: ZorahConfig;
  }
}

const Zorah: ZorahConfig = {
  translations: {
    en: {
      php: {
        auth: {
          failed: 'These credentials do not match our records.',
          password: 'The provided password is incorrect.',
          throttle: 'Too many login attempts. Please try again in :seconds seconds.',
        },
        base: {
          actions: {
            add: 'Add',
            cancel: 'Cancel',
            close: 'Close',
            confirm: 'Confirm',
            continue: 'Continue',
            create: 'Create',
            delete: 'Delete',
            done: 'Done',
            leave: 'Leave',
            more: 'More',
            remove: 'Remove',
            save: 'Save',
          },
          status: {
            added: 'Added.',
            copied: 'Copied!',
            copy_to_clipboard: 'Copy to clipboard',
            created: 'Created.',
            saved: 'Saved.',
            enabled: 'Enabled',
            disabled: 'Disabled',
            last_used: 'Last used',
          },
          nav: {
            dashboard: 'Dashboard',
            settings: 'Settings',
            settings_description: 'Manage your profile and account settings',
            documentation: 'Documentation',
            laracasts: 'Laracasts',
            navigation_menu: 'Navigation Menu',
            sidebar: 'Sidebar',
            toggle_sidebar: 'Toggle Sidebar',
            displays_mobile_sidebar: 'Displays the mobile sidebar.',
            platform: 'Platform',
            profile: 'Profile',
            two_factor: 'Two-Factor Auth',
            browser_sessions: 'Browser Sessions',
            appearance: 'Appearance',
          },
          welcome: {
            title: 'Welcome',
            get_started: "Let's get started",
            ecosystem_intro: 'Laravel has an incredibly rich ecosystem.',
            ecosystem_suggest: 'We suggest starting with the following.',
            read_the: 'Read the',
            watch_tutorials_at: 'Watch video tutorials at',
            deploy_now: 'Deploy now',
          },
          auth: {
            log_in: 'Log in',
            log_in_to_account: 'Log in to your account',
            log_out: 'Log out',
            sign_up: 'Sign up',
            register: 'Register',
            create_account: 'Create an account',
            create_account_description: 'Enter your details below to create your account',
            login_description: 'Enter your email and password below to log in',
            forgot_password: 'Forgot password?',
            forgot_password_description: 'Enter your email to receive a password reset link',
            reset_password: 'Reset password',
            reset_password_description: 'Please enter your new password below',
            remember_me: 'Remember me',
            confirm_password: 'Confirm Password',
            confirm_your_password: 'Confirm your password',
            secure_area: 'This is a secure area of the application. Please confirm your password before continuing.',
            or_return_to: 'Or, return to',
            welcome: 'Welcome',
            lets_get_started: "Let's get started",
          },
          verification: {
            title: 'Email verification',
            verify_email: 'Verify email',
            resend: 'Resend verification email',
            check_email: 'Please verify your email address by clicking on the link we just emailed to you.',
          },
          two_factor: {
            title: 'Two-Factor Authentication',
            description: 'Manage your two-factor authentication settings',
            enable: 'Enable 2FA',
            enable_description: 'Add an extra layer of security to your account by enabling two-factor authentication.',
            enabled_description:
              'With two-factor authentication enabled, you will be prompted for a secure, random pin during login, which you can retrieve from the TOTP-supported application on your phone.',
            disable: 'Disable 2FA',
            continue_setup: 'Continue Setup',
            regenerate_codes: 'Regenerate Codes',
            recovery_codes_title: '2FA Recovery Codes',
            recovery_codes_description: 'Recovery codes let you regain access if you lose your 2FA device. Store them in a secure password manager.',
            view_recovery_codes: 'View Recovery Codes',
            hide_recovery_codes: 'Hide Recovery Codes',
            recovery_codes_usage:
              'Each recovery code can be used once to access your account and will be removed after use. If you need more, click :link above.',
            enter_recovery_code: 'Enter recovery code',
            recovery_code: 'Recovery Code',
            recovery_code_description: 'Please confirm access to your account by entering one of your emergency recovery codes.',
            auth_code: 'Authentication Code',
            auth_code_description: 'Enter the authentication code provided by your authenticator application.',
            use_auth_code: 'login using an authentication code',
            use_recovery_code: 'login using a recovery code',
            or_you_can: 'or you can',
          },
          profile: {
            title: 'Profile Information',
            settings: 'Profile settings',
            description: 'Update your name and email address',
            manage_settings: 'Manage your profile and account settings',
            avatar: 'Avatar',
            select_photo: 'Select New Photo',
            remove_photo: 'Remove Photo',
          },
          password: {
            title: 'Update Password',
            settings: 'Password settings',
            description: 'Ensure your account is using a long, random password to stay secure',
            current: 'Current password',
            new: 'New password',
          },
          sessions: {
            title: 'Browser Sessions',
            description: 'Manage and log out your active sessions on other browsers and devices',
            info: 'If necessary, you may log out of all of your other browser sessions across all of your devices. Some of your recent sessions are listed below; however, this list may not be exhaustive. If you feel your account has been compromised, you should also update your password.',
            log_out_other: 'Log Out Other Browser Sessions',
            logout_other: 'Log Out Other Browser Sessions',
            log_out_confirm: 'Please enter your password to confirm you would like to log out of your other browser sessions.',
            this_device: 'This device',
            current_session: 'Your current browser session',
          },
          appearance: { title: 'Appearance settings', description: "Update your account's appearance settings" },
          delete_account: {
            title: 'Delete Account',
            description: 'Delete your account and all of its resources',
            confirm: 'Are you sure you want to delete your account?',
            confirm_title: 'Are you sure you want to delete your account?',
            confirm_description:
              'Once your account is deleted, all of its resources and data will also be permanently deleted. Please enter your password to confirm you would like to permanently delete your account.',
            warning:
              'Once your account is deleted, all of its resources and data will be permanently deleted. Before deleting your account, please download any data or information that you wish to retain.',
          },
          teams: {
            title: 'Team Settings',
            description: "Manage your team's settings and members",
            settings: 'Team Settings',
            settings_description: "Manage your team's settings and members",
            details: 'Team Details',
            details_description: "The team's name and owner information.",
            name: 'Team Name',
            name_description: "The team's name and owner information.",
            owner: 'Team Owner',
            role: 'Role',
            members: 'Team Members',
            members_description: 'All of the people that are part of this team.',
            add_member: 'Add Team Member',
            add_member_description: 'Add a new team member to your team, allowing them to collaborate with you.',
            add_member_email: 'Please provide the email address of the person you would like to add to this team.',
            remove_member: 'Remove Team Member',
            remove_member_confirm: 'Are you sure you would like to remove this person from the team?',
            pending_invitations: 'Pending Team Invitations',
            manage_role: 'Manage Role',
            manage_team: 'Manage Team',
            leave: 'Leave Team',
            leave_confirm: 'Are you sure you would like to leave this team?',
            switch: 'Switch Teams',
            switch_teams: 'Switch Teams',
            create: 'Create Team',
            create_new: 'Create New Team',
            create_description: 'Create a new team to collaborate with others',
            create_description_long: 'Create a new team to collaborate with others on projects.',
            delete: 'Delete Team',
            delete_description: 'Permanently delete this team.',
          },
          api_tokens: {
            title: 'API Tokens',
            description: 'API tokens allow third-party services to authenticate with our application on your behalf.',
            manage: 'Manage API Tokens',
            manage_description: 'Manage your API tokens for third-party access',
            create: 'Create API Token',
            created: 'API Token Created',
            created_description: "Please copy your new API token. For your security, it won't be shown again.",
            permissions: 'API Token Permissions',
            delete: 'Delete API Token',
            delete_confirm: 'Are you sure you would like to delete this API token?',
            delete_existing: 'You may delete any of your existing tokens if they are no longer needed.',
          },
          fields: {
            name: 'Name',
            full_name: 'Full name',
            email: 'Email',
            email_address: 'Email address',
            email_placeholder: 'email@example.com',
            password: 'Password',
            role: 'Role',
            permissions: 'Permissions',
            platform: 'Platform',
          },
          legal: { terms: 'Terms of Service', privacy: 'Privacy Policy' },
        },
        pagination: { previous: '&laquo; Previous', next: 'Next &raquo;' },
        passwords: {
          reset: 'Your password has been reset.',
          sent: 'We have emailed your password reset link.',
          throttled: 'Please wait before retrying.',
          token: 'This password reset token is invalid.',
          user: "We can't find a user with that email address.",
        },
        validation: {
          accepted: 'The :attribute field must be accepted.',
          accepted_if: 'The :attribute field must be accepted when :other is :value.',
          active_url: 'The :attribute field must be a valid URL.',
          after: 'The :attribute field must be a date after :date.',
          after_or_equal: 'The :attribute field must be a date after or equal to :date.',
          alpha: 'The :attribute field must only contain letters.',
          alpha_dash: 'The :attribute field must only contain letters, numbers, dashes, and underscores.',
          alpha_num: 'The :attribute field must only contain letters and numbers.',
          any_of: 'The :attribute field is invalid.',
          array: 'The :attribute field must be an array.',
          ascii: 'The :attribute field must only contain single-byte alphanumeric characters and symbols.',
          before: 'The :attribute field must be a date before :date.',
          before_or_equal: 'The :attribute field must be a date before or equal to :date.',
          between: {
            array: 'The :attribute field must have between :min and :max items.',
            file: 'The :attribute field must be between :min and :max kilobytes.',
            numeric: 'The :attribute field must be between :min and :max.',
            string: 'The :attribute field must be between :min and :max characters.',
          },
          boolean: 'The :attribute field must be true or false.',
          can: 'The :attribute field contains an unauthorized value.',
          confirmed: 'The :attribute field confirmation does not match.',
          contains: 'The :attribute field is missing a required value.',
          current_password: 'The password is incorrect.',
          date: 'The :attribute field must be a valid date.',
          date_equals: 'The :attribute field must be a date equal to :date.',
          date_format: 'The :attribute field must match the format :format.',
          decimal: 'The :attribute field must have :decimal decimal places.',
          declined: 'The :attribute field must be declined.',
          declined_if: 'The :attribute field must be declined when :other is :value.',
          different: 'The :attribute field and :other must be different.',
          digits: 'The :attribute field must be :digits digits.',
          digits_between: 'The :attribute field must be between :min and :max digits.',
          dimensions: 'The :attribute field has invalid image dimensions.',
          distinct: 'The :attribute field has a duplicate value.',
          doesnt_contain: 'The :attribute field must not contain any of the following: :values.',
          doesnt_end_with: 'The :attribute field must not end with one of the following: :values.',
          doesnt_start_with: 'The :attribute field must not start with one of the following: :values.',
          email: 'The :attribute field must be a valid email address.',
          encoding: 'The :attribute field must be encoded in :encoding.',
          ends_with: 'The :attribute field must end with one of the following: :values.',
          enum: 'The selected :attribute is invalid.',
          exists: 'The selected :attribute is invalid.',
          extensions: 'The :attribute field must have one of the following extensions: :values.',
          file: 'The :attribute field must be a file.',
          filled: 'The :attribute field must have a value.',
          gt: {
            array: 'The :attribute field must have more than :value items.',
            file: 'The :attribute field must be greater than :value kilobytes.',
            numeric: 'The :attribute field must be greater than :value.',
            string: 'The :attribute field must be greater than :value characters.',
          },
          gte: {
            array: 'The :attribute field must have :value items or more.',
            file: 'The :attribute field must be greater than or equal to :value kilobytes.',
            numeric: 'The :attribute field must be greater than or equal to :value.',
            string: 'The :attribute field must be greater than or equal to :value characters.',
          },
          hex_color: 'The :attribute field must be a valid hexadecimal color.',
          image: 'The :attribute field must be an image.',
          in: 'The selected :attribute is invalid.',
          in_array: 'The :attribute field must exist in :other.',
          in_array_keys: 'The :attribute field must contain at least one of the following keys: :values.',
          integer: 'The :attribute field must be an integer.',
          ip: 'The :attribute field must be a valid IP address.',
          ipv4: 'The :attribute field must be a valid IPv4 address.',
          ipv6: 'The :attribute field must be a valid IPv6 address.',
          json: 'The :attribute field must be a valid JSON string.',
          list: 'The :attribute field must be a list.',
          lowercase: 'The :attribute field must be lowercase.',
          lt: {
            array: 'The :attribute field must have less than :value items.',
            file: 'The :attribute field must be less than :value kilobytes.',
            numeric: 'The :attribute field must be less than :value.',
            string: 'The :attribute field must be less than :value characters.',
          },
          lte: {
            array: 'The :attribute field must not have more than :value items.',
            file: 'The :attribute field must be less than or equal to :value kilobytes.',
            numeric: 'The :attribute field must be less than or equal to :value.',
            string: 'The :attribute field must be less than or equal to :value characters.',
          },
          mac_address: 'The :attribute field must be a valid MAC address.',
          max: {
            array: 'The :attribute field must not have more than :max items.',
            file: 'The :attribute field must not be greater than :max kilobytes.',
            numeric: 'The :attribute field must not be greater than :max.',
            string: 'The :attribute field must not be greater than :max characters.',
          },
          max_digits: 'The :attribute field must not have more than :max digits.',
          mimes: 'The :attribute field must be a file of type: :values.',
          mimetypes: 'The :attribute field must be a file of type: :values.',
          min: {
            array: 'The :attribute field must have at least :min items.',
            file: 'The :attribute field must be at least :min kilobytes.',
            numeric: 'The :attribute field must be at least :min.',
            string: 'The :attribute field must be at least :min characters.',
          },
          min_digits: 'The :attribute field must have at least :min digits.',
          missing: 'The :attribute field must be missing.',
          missing_if: 'The :attribute field must be missing when :other is :value.',
          missing_unless: 'The :attribute field must be missing unless :other is :value.',
          missing_with: 'The :attribute field must be missing when :values is present.',
          missing_with_all: 'The :attribute field must be missing when :values are present.',
          multiple_of: 'The :attribute field must be a multiple of :value.',
          not_in: 'The selected :attribute is invalid.',
          not_regex: 'The :attribute field format is invalid.',
          numeric: 'The :attribute field must be a number.',
          password: {
            letters: 'The :attribute field must contain at least one letter.',
            mixed: 'The :attribute field must contain at least one uppercase and one lowercase letter.',
            numbers: 'The :attribute field must contain at least one number.',
            symbols: 'The :attribute field must contain at least one symbol.',
            uncompromised: 'The given :attribute has appeared in a data leak. Please choose a different :attribute.',
          },
          present: 'The :attribute field must be present.',
          present_if: 'The :attribute field must be present when :other is :value.',
          present_unless: 'The :attribute field must be present unless :other is :value.',
          present_with: 'The :attribute field must be present when :values is present.',
          present_with_all: 'The :attribute field must be present when :values are present.',
          prohibited: 'The :attribute field is prohibited.',
          prohibited_if: 'The :attribute field is prohibited when :other is :value.',
          prohibited_if_accepted: 'The :attribute field is prohibited when :other is accepted.',
          prohibited_if_declined: 'The :attribute field is prohibited when :other is declined.',
          prohibited_unless: 'The :attribute field is prohibited unless :other is in :values.',
          prohibits: 'The :attribute field prohibits :other from being present.',
          regex: 'The :attribute field format is invalid.',
          required: 'The :attribute field is required.',
          required_array_keys: 'The :attribute field must contain entries for: :values.',
          required_if: 'The :attribute field is required when :other is :value.',
          required_if_accepted: 'The :attribute field is required when :other is accepted.',
          required_if_declined: 'The :attribute field is required when :other is declined.',
          required_unless: 'The :attribute field is required unless :other is in :values.',
          required_with: 'The :attribute field is required when :values is present.',
          required_with_all: 'The :attribute field is required when :values are present.',
          required_without: 'The :attribute field is required when :values is not present.',
          required_without_all: 'The :attribute field is required when none of :values are present.',
          same: 'The :attribute field must match :other.',
          size: {
            array: 'The :attribute field must contain :size items.',
            file: 'The :attribute field must be :size kilobytes.',
            numeric: 'The :attribute field must be :size.',
            string: 'The :attribute field must be :size characters.',
          },
          starts_with: 'The :attribute field must start with one of the following: :values.',
          string: 'The :attribute field must be a string.',
          timezone: 'The :attribute field must be a valid timezone.',
          unique: 'The :attribute has already been taken.',
          uploaded: 'The :attribute failed to upload.',
          uppercase: 'The :attribute field must be uppercase.',
          url: 'The :attribute field must be a valid URL.',
          ulid: 'The :attribute field must be a valid ULID.',
          uuid: 'The :attribute field must be a valid UUID.',
          custom: { 'attribute-name': { 'rule-name': 'custom-message' } },
          attributes: [],
        },
      },
      json: [],
    },
  },
};

if (typeof window !== 'undefined' && typeof window.Zorah !== 'undefined') {
  Object.assign(Zorah.translations, window.Zorah.translations);
}

export { Zorah };
