name: Lint

on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
        default: ''

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          bun i

      - name: Run Fixr
        run: vendor/bin/fixr

      - name: Format Frontend
        run: bun run format

      - name: Lint Frontend
        run: bun run lint

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: 'chore(style): fix code style'
          commit_options: '--no-verify'
